name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - Production  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Or the version you're using

      # Navigate to the 'home-web' directory and run npm commands
      - name: Install dependencies
        run: |
          cd home-web  # Adjust path as needed
          npm install

      - name: Build the app
        run: |
          cd home-web  # Adjust path as needed
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          cd home-web  # Adjust path as needed
          npm run deploy
        env:
          CI: false  # Optional: This disables any interactive prompts in GitHub Actions
