name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - Production  # Or the branch you're using

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Or whichever version you're using

      # Navigate to the 'test_reactjs/tree/Production/home-web' directory
      - name: Change directory to home-web
        run: cd test_reactjs/tree/Production/home-web

      - name: Install dependencies
        run: |
          cd test_reactjs/tree/Production/home-web  # Navigate to your app directory
          npm install

      - name: Build the app
        run: |
          cd test_reactjs/tree/Production/home-web  # Navigate to your app directory
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          cd test_reactjs/tree/Production/home-web  # Navigate to your app directory
          npm run deploy
        env:
          CI: false  # Optional: This disables any interactive prompts in GitHub Actions
