name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - Production  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Or the version you're using

      # Navigate to the 'home-web' directory and install dependencies
      - name: Install dependencies
        run: |
          cd test_reactjs/tree/Production/home-web  # Adjust path if necessary
          npm install

      - name: Build the app
        run: |
          cd test_reactjs/tree/Production/home-web  # Adjust path if necessary
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          cd test_reactjs/tree/Production/home-web  # Adjust path if necessary
          npm run deploy  # This will run the 'gh-pages -d build' command
        env:
          CI: false  # Optional: This disables any interactive prompts in GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass GitHub Token to gh-pages
